sculpin_content_types:
  posts:
    permalink: blog/:year/:month/:day/:filename/

sculpin_theme:
  theme:
    toby-griffiths/2016

sculpin_twig:
  extensions:  ['', 'html.twig', 'xml.twig', 'twig', 'html']