# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: TobyG.net
subtitle: Ramblings of an environmentally friendly, web geek, and his amazing friends

social:
  twitter: ToG

# Insert your disqus shortname
disqus:
  shortname:  tobyg-net

links:
  - href: https://twitter.com
    text: @ToG